// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gondor_chic_back.Data;

#nullable disable

namespace gondor_chic_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525123431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gondor_chic_back.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MotDePasse = "!totoXXS",
                            Nom = "Sacquet",
                            Prenom = "Frodon",
                            Pseudo = "Leporteur"
                        },
                        new
                        {
                            Id = 2,
                            MotDePasse = "titiXXL",
                            Nom = "Gamegie",
                            Prenom = "Sam",
                            Pseudo = "Lebrave"
                        },
                        new
                        {
                            Id = 3,
                            MotDePasse = "tataXS!",
                            Nom = "Brandebouc",
                            Prenom = "Elian",
                            Pseudo = "Lefort"
                        });
                });

            modelBuilder.Entity("gondor_chic_back.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstDuJour")
                        .HasColumnType("bit");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstDuJour = true,
                            ImageLink = "https://media.istockphoto.com/id/1476477778/fr/vectoriel/chaudron-noir-r%C3%A9aliste-3d-dans-un-style-minimaliste-de-dessin-anim%C3%A9-pot-m%C3%A9di%C3%A9val-en-fer.jpg?s=612x612&w=0&k=20&c=ZY6WPyQDvGruzPFi7XWWxJv6IsieMU_Zfvz7cAQESqw=",
                            Libelle = "Chaudron magique",
                            Prix = 30000m,
                            Quantite = 678
                        },
                        new
                        {
                            Id = 2,
                            EstDuJour = false,
                            ImageLink = "https://cinereplicas.fr/cdn/shop/files/LOTR-Hobbit-Cloak-Product-_1-4895205611160-CR1252.jpg?v=1724041629",
                            Libelle = "Cape de voyage",
                            Prix = 800m,
                            Quantite = 521
                        },
                        new
                        {
                            Id = 3,
                            EstDuJour = false,
                            ImageLink = "https://thumbs.dreamstime.com/b/tasse-vide-de-terre-cuite-ou-caf%C3%A9-d-argile-pot-verre-%C3%A0-boire-brun-111137274.jpg",
                            Libelle = "Mug en terre",
                            Prix = 5m,
                            Quantite = 433
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
